<sidebar id="mageziner" class="mageziner">
  <button class="js-mgz-close mgz-close" type="button">
    <svg class="nc-icon glyph" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" width="16px" height="16px" viewBox="0 0 16 16"><g> <path fill="#444444" d="M5,5V1c0-0.6-0.4-1-1-1S3,0.4,3,1v4c0,0.6,0.4,1,1,1S5,5.6,5,5z"></path> <path fill="#444444" d="M1,11c0,1.3,0.9,2.4,2,2.8c0,0.1,0,0.1,0,0.2v1c0,0.6,0.4,1,1,1s1-0.4,1-1v-1c0-0.1,0-0.1,0-0.2 c1.2-0.4,2-1.5,2-2.8c0-1.7-1.3-3-3-3S1,9.3,1,11z"></path> <path data-color="color-2" fill="#444444" d="M11,11v4c0,0.6,0.4,1,1,1s1-0.4,1-1v-4c0-0.6-0.4-1-1-1S11,10.4,11,11z"></path> <path data-color="color-2" fill="#444444" d="M9,5c0,1.7,1.3,3,3,3s3-1.3,3-3c0-1.3-0.9-2.4-2-2.8c0-0.1,0-0.1,0-0.2V1c0-0.6-0.4-1-1-1 s-1,0.4-1,1v1c0,0.1,0,0.1,0,0.2C9.9,2.6,9,3.7,9,5z"></path> </g></svg>
    <span><?php echo __('Mageziner') ?></span>
  </button>
  <div class="mageziner__container">
  <header class="mageziner__header">
    <h2><?php echo __('Mageziner') ?></h2>
    <button class="js-mgz-close mgz-button--transparent" type="button">
      <svg class="nc-icon glyph" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" width="16px" height="16px" viewBox="0 0 16 16"><g> <path fill="#444444" d="M14.7,1.3c-0.4-0.4-1-0.4-1.4,0L8,6.6L2.7,1.3c-0.4-0.4-1-0.4-1.4,0s-0.4,1,0,1.4L6.6,8l-5.3,5.3 c-0.4,0.4-0.4,1,0,1.4C1.5,14.9,1.7,15,2,15s0.5-0.1,0.7-0.3L8,9.4l5.3,5.3c0.2,0.2,0.5,0.3,0.7,0.3s0.5-0.1,0.7-0.3 c0.4-0.4,0.4-1,0-1.4L9.4,8l5.3-5.3C15.1,2.3,15.1,1.7,14.7,1.3z"></path> </g></svg>
    </button>
  </header>

  <nav class="mageziner__nav--tabs">
    <ul>
      <li><button class="active" type="button" aria-controls="tab-theme" aria-expanded="true">
        <svg class="nc-icon glyph" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" width="16px" height="16px" viewBox="0 0 16 16"><g> <path fill="#444444" d="M15,0H3C2.4,0,2,0.4,2,1v1H1C0.4,2,0,2.4,0,3v6c0,0.6,0.4,1,1,1h6v6h4V9c0-0.6-0.4-1-1-1H2V5 c0,0.6,0.4,1,1,1h12c0.6,0,1-0.4,1-1V1C16,0.4,15.6,0,15,0z"></path> <path data-color="color-2" fill="#444444" d="M12,12.1c0,1.1,0.9,1.9,2,1.9s2-0.9,2-1.9c0-1.1-2-3.9-2-3.9S12,11,12,12.1z"></path> </g></svg>
        <span><?php echo __('Theme') ?></span>
      </button></li>
      <li><button type="button" aria-controls="tab-blocks">
        <svg class="nc-icon glyph" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" width="16px" height="16px" viewBox="0 0 16 16"><g> <path fill="#444444" d="M6,9H1C0.448,9,0,8.552,0,8V1c0-0.552,0.448-1,1-1h5c0.552,0,1,0.448,1,1v7C7,8.552,6.552,9,6,9z"></path> <path data-color="color-2" fill="#444444" d="M6,16H1c-0.552,0-1-0.448-1-1v-3c0-0.552,0.448-1,1-1h5c0.552,0,1,0.448,1,1v3 C7,15.552,6.552,16,6,16z"></path> <path data-color="color-2" fill="#444444" d="M15,6h-5C9.448,6,9,5.552,9,5V1c0-0.552,0.448-1,1-1h5c0.552,0,1,0.448,1,1v4 C16,5.552,15.552,6,15,6z"></path> <path fill="#444444" d="M15,16h-5c-0.552,0-1-0.448-1-1V9c0-0.552,0.448-1,1-1h5c0.552,0,1,0.448,1,1v6C16,15.552,15.552,16,15,16z"></path> </g></svg>
        <span><?php echo __('Blocks') ?></span>
      </button></li>
    </ul>
  </nav>

  <div class="mageziner__panels">
    <div id="tab-theme" class="mageziner__panel">
      <section class="mageziner__section">
        <h2 class="mageziner__title peekaboo"><?php echo __('Branding') ?></h2>
        <ul class="mgz-options">
          <li>
            <label class="mgz-option__label">
              Logo
            </label>
            <input class="js-mgz-input" type="url" placeholder="https://magento.com/sites/all/themes/mag_redesign/images/magento-logo.svg" data-var=".logo img" data-type="img" />
          </li>
        </ul>
      </section>
      <section class="mageziner__section">
        <h2 class="mageziner__title peekaboo"><?php echo __('Colors') ?></h2>
        <ul class="mgz-options">
          <li>
            <label class="mgz-option__label">Red Color</label>
            <div class="mgz-color-input">
              <input class="js-mgz-input" type="color" name="color__red" data-var="--color-red" data-type="css" />
              <input class="js-mgz-input" type="text" data-var="--color-red" data-type="css" disabled />
            </div>
          </li>
          <li>
            <label class="mgz-option__label">Green Color</label>
            <div class="mgz-color-input">
              <input class="js-mgz-input" type="color" name="color__green" data-var="--color-green" data-type="css" />
              <input class="js-mgz-input" type="text" data-var="--color-green" data-type="css" disabled />
            </div>
          </li>
          <li>
            <label class="mgz-option__label">Orange Color</label>
            <div class="mgz-color-input">
              <input class="js-mgz-input" type="color" name="color__orange" data-var="--color-orange" data-type="css" />
              <input class="js-mgz-input" type="text" data-var="--color-orange" data-type="css" disabled />
            </div>
          </li>
          <li>
            <label class="mgz-option__label">Blue Color</label>
            <div class="mgz-color-input">
              <input class="js-mgz-input" type="color" name="color__blue" data-var="--color-blue" data-type="css" />
              <input class="js-mgz-input" type="text" data-var="--color-blue" data-type="css" disabled />
            </div>
          </li>
          <li>
            <label class="mgz-option__label">Primary Color</label>
            <div class="mgz-color-input">
              <input class="js-mgz-input" type="color" name="color__primary" data-var="--color-primary" data-type="css" />
              <input class="js-mgz-input" type="text" data-var="--color-primary" data-type="css" disabled />
            </div>
          </li>
          <li><label class="mgz-option__label">Secondary Color</label>
            <div class="mgz-color-input">
              <input class="js-mgz-input" type="color" name="color__secondary" data-var="--color-secondary" data-type="css" />
              <input class="js-mgz-input" type="text" data-var="--color-secondary" data-type="css" disabled />
            </div>
          </li>
                    <li>
            <label class="mgz-option__label">Border Color</label>
            <div class="mgz-color-input">
              <input class="js-mgz-input" type="color" name="color__border" data-var="--color-border" data-type="css" />
              <input class="js-mgz-input" type="text" data-var="--color-border" data-type="css" disabled />
            </div>
          </li>
          <li><label class="mgz-option__label">Gray Light</label>
            <div class="mgz-color-input">
              <input class="js-mgz-input" type="color" name="color__gray-light" data-var="--color-gray-light" data-type="css" />
              <input class="js-mgz-input" type="text" data-var="--color-gray-light" data-type="css" disabled />
            </div>
          </li>
          <li><label class="mgz-option__label">Gray Medium</label>
            <div class="mgz-color-input">
              <input class="js-mgz-input" type="color" name="color__gray-medium" data-var="--color-gray-medium" data-type="css" />
              <input class="js-mgz-input" type="text" data-var="--color-gray-medium" data-type="css" disabled />
            </div>
          </li>
          <li><label class="mgz-option__label">Gray Dark</label>
            <div class="mgz-color-input">
              <input class="js-mgz-input" type="color" name="color__gray-dark" data-var="--color-gray-dark" data-type="css" />
              <input class="js-mgz-input" type="text" data-var="--color-gray-dark" data-type="css" disabled />
            </div>
          </li>
          <li><label class="mgz-option__label">Text Color</label>
            <div class="mgz-color-input">
              <input class="js-mgz-input" type="color" name="color__text" data-var="--color-text" data-type="css" />
              <input class="js-mgz-input" type="text" data-var="--color-text" data-type="css" disabled />
            </div>
          </li>
          <li><label class="mgz-option__label">Secondary Nav Link Color</label>
            <div class="mgz-color-input">
              <input class="js-mgz-input" type="color" name="color__color-nav" data-var="--color-nav" data-type="css" />
              <input class="js-mgz-input" type="text" data-var="--color-nav" data-type="css" disabled />
            </div>
          </li>
          <li><label class="mgz-option__label">Link Color</label>
            <div class="mgz-color-input">
              <input class="js-mgz-input" type="color" name="color__link" data-var="--color-link" data-type="css" />
              <input class="js-mgz-input" type="text" data-var="--color-link" data-type="css" disabled />
            </div>
          </li>
        </ul>

      </section>
      <section class="mageziner__section">
        <h2 class="mageziner__title peekaboo"><?php echo __('Typography') ?></h2>

        <ul class="mgz-options">
          <li>
            <label class="mgz-option__label">Primary Font</label>
            <select class="js-mgz-input js-font-data" name="font__primary" data-var="--font-primary" data-type="font">
            </select>
          </li>

          <li>
            <label class="mgz-option__label">Secondary Font</label>
            <label class="mgz-checkbox"><input type="checkbox" checked /> Use Primary Font</label>
          </li>

          <li>
            <label class="mgz-option__label">Body Font Size</label>
            <input class="js-mgz-input" type="text" placeholder="16px" data-var="--font-size--body" data-type="css" />
          </li>
      </section>
    </div>

    <div id="tab-blocks" class="mageziner__panel">
      <p><svg class="nc-icon glyph" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" width="24px" height="24px" viewBox="0 0 24 24"><g> <path fill="#ffffff" d="M12,0C6.4858398,0,2,4.4858398,2,10v12c0,0.3466797,0.1796875,0.668457,0.4741211,0.8505859 c0.2954102,0.1821289,0.6630859,0.1982422,0.9731445,0.0439453l3.5981445-1.7993164l4.5830078,1.8334961 c0.2392578,0.0947266,0.5039062,0.0947266,0.7431641,0l4.5830078-1.8334961l3.5981445,1.7993164 C20.6938477,22.9648438,20.847168,23,21,23c0.1826172,0,0.3652344-0.050293,0.5258789-0.1494141 C21.8203125,22.668457,22,22.3466797,22,22V10C22,4.4858398,17.5141602,0,12,0z M8,13c-1.1045532,0-2-0.8954468-2-2 c0-1.1046143,0.8954468-2,2-2s2,0.8953857,2,2C10,12.1045532,9.1045532,13,8,13z M16,13c-1.1045532,0-2-0.8954468-2-2 c0-1.1046143,0.8954468-2,2-2s2,0.8953857,2,2C18,12.1045532,17.1045532,13,16,13z"></path> </g></svg> No blocks found...</p>
    </div>
  </div>

  <button class="js-mgz-reset" type="button"><?php echo __('Reset') ?></button>

  <footer class="mageziner__footer">
    <div class="mageziner__copyright">Made by <a href="http://gil.nyc">Gil</a> <a href="http://wwf.panda.org/what_we_do/endangered_species/giant_panda/" rel="noopener noreferrer" target="_blank">🐼</a></div>
    <pre><br>░░░░░░░░▄██▄░░░░░░▄▄░░<br>░░░░░░░▐███▀░░░░░▄███▌<br>░░▄▀░░▄█▀▀░░░░░░░░▀██░<br>░█░░░██░░░░░░░░░░░░░░░<br>█▌░░▐██░░▄██▌░░▄▄▄░░░▄<br>██░░▐██▄░▀█▀░░░▀██░░▐▌<br>██▄░▐███▄▄░░▄▄▄░▀▀░▄██<br>▐███▄██████▄░▀░▄█████▌<br>▐████████████▀▀██████░<br>░▐████▀██████░░█████░░<br>░░░▀▀▀░░█████▌░████▀░░<br>░░░░░░░░░▀▀███░▀▀▀░░░░ </pre>
  </footer>
    </div>
</sidebar>


<script>
/*

WARNING. SHIT IS POORLY CODED. 💩

*/

require(['jquery', 'mageziner/select2', 'mageziner/peekaboo', 'webfont'], function($, select2, peekaboo, WebFont) {

  function toggleSections(e) {
    // We're opening
    if ($(this).attr('aria-expanded') === 'true') {
      // Close any other things that were already open
      $('.mageziner__title.peekaboo button[aria-expanded="true"]').not(this).trigger('click.peekaboo');
    }
  }

  function toggleTabs(e) {
    // We're opening
    if ($(this).attr('aria-expanded') === 'true') {
      // Close any other things that were already open
      $('.mageziner__nav--tabs button[aria-expanded="true"]').not(this).trigger('click.peekaboo');
    }
  }

  var magezinerData = {};

  $(document).ready(function () {
    $('.mageziner__nav--tabs button').peekaboo({ callback: toggleTabs }); // init peekaboo for tabs

    populateMagezinerFromCSS();
    populateMagezinerFromSession();
    importBlocks();

    $('body').addClass('mageziner-loaded');

    $(document).on('click', '.js-mgz-reset', resetMageziner);
  });

  /*
      Google Font Loader
  */
  // Load a Google font by name.
  function loadFont(font) {
    WebFont.load({
      google: {
        families: [font]
      }
    });
  };

  /*
      Mageziner Data Logic
  */
  $(document).on('click', '.js-mgz-close', function () {
    $('#mageziner').toggleClass('mageziner--open');
  });

  $(document).on('change', '.js-mgz-input', function () {
    var $this = $(this);

    // if (!$this.val()) {
    //   return false;
    // }

    updateDOMData($this);
  });

  // change color input & picker together
  $(document).on('change', '.mgz-color-input input', function () {
    if ($(this).attr('type') == 'color') {
      $(this).siblings('[type="text"]').val($(this).val());
    } else if ($(this).attr('type') == 'text') {
      $(this).siblings('[type="color"]').val($(this).val());
    }
  });

  function updateDOMData(element) {
    var optionType = element.data('type');
    var optionVar = element.data('var');
    var optionValue = element.val();

    if (!optionValue) {
      return false;
    }

    if (optionType == 'css') {
      document.documentElement.style.setProperty(optionVar, optionValue);
    } else if (optionType == 'img') {
      // TODO: Check for valid URL string or even better CURL img to ensure it exists
      // $(this).attr('placeholder')
      $(optionVar).attr('src', optionValue);
    } else if (optionType == 'font') {
      loadFont(optionValue);
      document.documentElement.style.setProperty(optionVar, optionValue);
      // text.style.fontFamily = font;
    }

    magezinerData[optionVar] = optionValue;
    updateMagezinerData();
  }

  /*
      Storage
   */
  function updateMagezinerData() {
    // Stringify Object & Store it
    localStorage.setItem('mageziner-data', JSON.stringify(magezinerData));
  }

  function getMagezinerData() {
    // READ STRING FROM LOCAL STORAGE
    var magezinerStoreData = localStorage.getItem('mageziner-data');

    if (!magezinerStoreData) {
      return false;
    }

    // CONVERT STRING TO REGULAR JS OBJECT
    var magezinerObj = JSON.parse(magezinerStoreData);

    return magezinerObj;
  }

  function populateMagezinerFromCSS() {
    $('.js-mgz-input[type="text"]').each(function() {
      var inputName = $(this).data('var');
      var inputType = $(this).data('type');
      var themeValue = getComputedStyle(document.body).getPropertyValue(inputName);

      if (inputType == 'css' && themeValue.length) {
        $(this).val(themeValue);

        if ($(this).parent().hasClass('mgz-color-input')) {
          console.log('setting color');
          $(this).siblings('[type="color"]').val(themeValue);
        }
      }
    });
  }

  function populateMagezinerFromSession() {
    var data = getMagezinerData();
    magezinerData = data || {};

    if (!data) {
      $('body').addClass('mageziner-loaded');
      return false;
    }

    $('.js-mgz-input').each(function () {
      var inputName = $(this).data('var');

      if (data.hasOwnProperty(inputName)) {
        $(this).val(data[inputName]);
        updateDOMData($(this));
      }
    });

    // DEBUG SHOW DATA
    console.log(data);
  }

  /*
    Populate Font Select with Google Font Choices
  */
  var loadGoogleFonts = $.get("https://www.googleapis.com/webfonts/v1/webfonts?sort=popularity&key=<?php echo $block->getConfig('design/mageziner/api_google'); ?>", function (data) {

    var fonts = [];

    $.each(data.items, function (index, value) {
      fonts.push(value.family);
    });

    $(".js-font-data").select2({ data: fonts });

    // TODO: Select font value if in localstorage
  }).always(function () {
    //console.log('checked google fonts');
  });

  // Reset
  function resetMageziner() {
    if (confirm('Are you sure you want to reset ALL Mageziner options to their default values?')) {
      localStorage.removeItem('mageziner-data');
      window.location.reload(false);
    }
  }

  function removeNoBlogsMsg() {
    $('#tab-blocks > p').remove();
  }

  function injectSection(key, title) {
    var section = `
      <section data-key="${key}" class="mageziner__section">
          <h2 class="mageziner__title peekaboo">${title}</h2>
          <ul class="mgz-options"></ul>
      </section>
    `;

    var $blockContainer = $('.mageziner__container #tab-blocks');
    $blockContainer.append(section);
  }

  function injectField(key, label, type, cssVariable, dataType) {
    var $section = $(`.mageziner__container #tab-blocks section[data-key="${key}"] .mgz-options`);

    var field = `<li>`;
    field += `<label class="mgz-option__label">${label}</label>`;

    field += `
        <div class="mgz-color-input">
          <input class="js-mgz-input" type="${type}" name="color__primary" data-var="${cssVariable}" data-type="${dataType}">
          <input class="js-mgz-input" type="text" data-var="${cssVariable}" data-type="${dataType}" disabled="">
        </div>`;

    field += `</li>`;

    $section.append(field);
  }

  function injectHeading(key, headingLabel) {
    var $section = $(`.mageziner__container #tab-blocks section[data-key="${key}"] .mgz-options`);
    var heading = `<li><h4>${headingLabel}</h4></li>`;

    $section.append(heading);
  }

  // JSON DATA IMPORT
  function importBlocks() {
    $.getJSON("<?php echo $block->getViewFileUrl('Gil_Mageziner::data/blocks.json'); ?>", function(data) {
      var blocks = data.blocks;

      if (Object.keys(blocks).length > 0) {
        removeNoBlogsMsg();
      }

      $.each( blocks, function( key, val ) {
        var title = val.title;
        var fields = val.fields;
        var sectionKey = key;

        injectSection(key, title);

        $.each( fields, function( key, val ) {
          var label = val.label;
          var type = val.type;

          if (type != 'heading') {
            var cssVariable = val.cssVar;
            var dataType = val.dataType;

            injectField(sectionKey, label, type, cssVariable, dataType);
          } else {
            injectHeading(sectionKey, label)
          }
        });
      });

      $('.peekaboo').peekaboo({ callback: toggleSections }); // init peekaboo for global
    });
  }
});
</script>
